{% set version = "0.5.8" %}
{% set hash_value = "6d0925190a846e28412814ea50fa8b3d7969859bac8a93ebc5b2f1c0a1a34d6a" %}

package:
  name: wand
  version: '{{ version }}'

source:
  url: https://github.com/emcconville/wand/releases/download/{{ version }}/Wand-{{ version }}.tar.gz
  sha256: '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python
    - pip

  run:
    - python
    - imagemagick

test:
  imports:
    - wand.image

about:
  home: https://github.com/emcconville/wand
  license: MIT
  summary: 'Wand is a ctypes-based simple ImageMagick binding for Python, supporting 2.7, 3.6+, and PyPy'
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - r78v10a07
