{% set version = "0.5.7" %}
{% set hash_value = "13a96818a2f89e7684704ba3bfc20bdb21a15e08736c3fdf74035eeaeefd7873" %}

package:
  name: wand
  version: '{{ version }}'

source:
  url: https://github.com/emcconville/wand/releases/download/{{ version }}/Wand-{{ version }}.tar.gz
  sha256: '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python
    - pip

  run:
    - python
    - imagemagick

test:
  imports:
    - wand.image

about:
  home: https://github.com/emcconville/wand
  license: MIT
  summary: 'Wand is a ctypes-based simple ImageMagick binding for Python, supporting 2.7, 3.6+, and PyPy'
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - r78v10a07
