{% set version = "0.6.2" %}

package:
  name: wand
  version: {{ version }}

source:
  url: https://github.com/emcconville/wand/releases/download/{{ version }}/Wand-{{ version }}.tar.gz
  sha256: 65440e478b595aaa18483e25091adacf6d4458c49c2fd8d59e0fd44a7393a14a

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - python
    - pip

  run:
    - python
    - imagemagick

test:
  imports:
    - wand.image

about:
  home: https://github.com/emcconville/wand
  license: MIT
  summary: Wand is a ctypes-based simple ImageMagick binding for Python, supporting 2.7, 3.6+, and PyPy
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - r78v10a07
